<a href="https://colab.research.google.com/github/SvanaBirgis/Reiknifraedi/blob/main/Skilaverkefni/S7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Stærðfræði og reiknifræði vor 2022, skiladæmi 7, fyrri hluti (V25)**

Nafn: Svana Björg Birgisdóttir

Samverkamenn:

# Verkefni 25 - Reikningar með NumPy 

> Indented block





In [ ]:
import numpy as np

a = np.array([3,2,8])
b = np.array([2,0,1])
c = np.array([-2,1,5])

A = np.array([[2,4,7],
              [3,4,8],
              [4,6,9]])
B = np.array([[5,5,5],
              [6,6,6],
              [7,8,9]])

In [ ]:
# a
import numpy.linalg as la

before = a@b
over = c@(B@b)
under = 3*(la.norm(c))

print(before-over/under)

7.731619619663099


In [ ]:
# b

print(2*(A.T + (la.matrix_power(B, 2)))*(a-2*b))

[[-184  392 1248]
 [-224  472 1512]
 [-306  652 2076]]


In [ ]:
# c

print(f'det(A): {la.det(A)}')

print(f'Inverted: {la.inv(A)}')

det(A): 10.000000000000002
Inverted: [[-1.2  0.6  0.4]
 [ 0.5 -1.   0.5]
 [ 0.2  0.4 -0.4]]


In [ ]:
# d

print(la.solve(A,b))

[-2.   1.5  0. ]


In [ ]:
# e
p = np.array([[1,1], 
              [5,10]])
q = np.array([23, 170])
svar = la.solve(p,q)

print(f'Fimmkallar: {svar[0]}') #5 kallar
print(f'Tíkallar: {svar[1]}') #10 kallar

Fimmkallar: 12.0
Tíkallar: 11.0


In [ ]:
#2
def leysa(n):
   A = np.zeros((n,n))
   b = np.zeros((n,1))
   for i in range(n):
      for j in range(0,i-1):
        A[n-1,j] = 2            
      A[i,i] = 1  
   b[n-1] = -2
   x = la.solve(A, b)
   return x

leysa(4)

array([[ 0.],
       [ 0.],
       [ 0.],
       [-2.]])